name: CI

on:
  push:
    branches: [ master ]

jobs:
  checkstyle:
    name: Check styling
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install node modules
        run: npm install

      - name: Run lint
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install node modules
        run: npm install

      - name: Build
        run: npm run build
